version: '3.9'

services:
  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
