version: '3.9'

services:
  whisper-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]  # Utilisation du GPU 0
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(`192.168.252.12`)"
      - "traefik.http.services.whisper.loadbalancer.server.port=8081"

  whisper-api-2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["1"]  # Utilisation du GPU 1
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(`192.168.252.12`)"
      - "traefik.http.services.whisper.loadbalancer.server.port=8081"

  nginx:
    image: nginx:latest
    container_name: nginx-server
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`192.168.252.13`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    volumes:
      - ./html:/usr/share/nginx/html

  traefik:
    image: traefik:v2.10  # Version mise à jour
    container_name: traefik
    command:
      - "--api.insecure=true"  # À sécuriser en production ou désactiver
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"    # HTTP
      - "8080:8080"  # API Traefik (insecure, attention en prod)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Nécessaire pour que Traefik puisse détecter les services Docker
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true