version: '3.9'

services:
  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
