version: '3.9'

services:
  whisper-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]  # Utilisation du GPU 0
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(`192.168.252.12`)"
      - "traefik.http.services.whisper.loadbalancer.server.port=8081"

  whisper-api-2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["1"]  # Utilisation du GPU 1
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(`192.168.252.12`)"
      - "traefik.http.services.whisper.loadbalancer.server.port=8081"

  nginx:
    image: nginx:latest
    container_name: nginx-server
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`192.168.252.13`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    volumes:
      - ./html:/usr/share/nginx/html

networks:
  traefik-net:
    external: true