version: '3.9'

services:
  whisper-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8081:8081
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]
