version: '3.9'

services:
  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`whisper`)"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8081"

networks:
  traefik-net:
    external: true
