version: '3.9'

services:
  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - 8000:8000
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
